const IMG = {
  coffee1: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800&q=80",
  coffee2: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&q=80",
  coffee3: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=800&q=80",
  coffee4: "https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=800&q=80",
  coffee5: "https://images.unsplash.com/photo-1511920170033-f8396924c348?w=800&q=80",
  coffee6: "https://images.unsplash.com/photo-1559496417-e7f25cb247f3?w=800&q=80",
  bar1: "https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=800&q=80",
  bar2: "https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=800&q=80",
  bar3: "https://images.unsplash.com/photo-1572116469696-31de0f17cc34?w=800&q=80",
  bar4: "https://images.unsplash.com/photo-1543007630-9710e4a00a20?w=800&q=80",
  food1: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80",
  food2: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800&q=80",
  food3: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&q=80",
  food4: "https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?w=800&q=80",
  food5: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=800&q=80",
  food6: "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=800&q=80",
  brunch1: "https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?w=800&q=80",
  brunch2: "https://images.unsplash.com/photo-1525351484163-7529414344d8?w=800&q=80",
  brunch3: "https://images.unsplash.com/photo-1484723091739-30a097e8f929?w=800&q=80",
  pizza1: "https://images.unsplash.com/photo-1565299507177-b0ac66763828?w=800&q=80",
  pizza2: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800&q=80",
  italian1: "https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=800&q=80",
  italian2: "https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=800&q=80",
  beer1: "https://images.unsplash.com/photo-1535958636474-b021ee887b13?w=800&q=80",
  beer2: "https://images.unsplash.com/photo-1436076863939-06870fe779c2?w=800&q=80",
  street1: "https://images.unsplash.com/photo-1601050690117-94f5f6fa8bd7?w=800&q=80",
  street2: "https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=800&q=80",
  dessert1: "https://images.unsplash.com/photo-1551024506-0bccd828d307?w=800&q=80",
  dessert2: "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800&q=80",
  late1: "https://images.unsplash.com/photo-1552566626-52f8b828add9?w=800&q=80",
  late2: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&q=80",
};

export const DEV_LISTS = [
  {
    id: "dev-1",
    title: "Best Coffee in Bangalore",
    description: "From pour-overs to filter kaapi — the spots that keep me caffeinated across the city",
    slug: "best-coffee-bangalore",
    emoji: "☕",
    coverStyle: 0,
    placeCount: 8,
    saveCount: 142,
    createdAt: "2026-05-10T10:00:00Z",
    isPublished: true,
    isHot: true,
    authorHandle: "priya",
    authorName: "Priya Sharma",
    authorAvatarUrl: null,
    heroPhotoRef: IMG.coffee1,
  },
  {
    id: "dev-2",
    title: "Date Night Spots",
    description: "Candlelit corners and rooftop cocktails worth dressing up for",
    slug: "date-night-spots",
    emoji: "🍸",
    coverStyle: 1,
    placeCount: 8,
    saveCount: 89,
    createdAt: "2026-05-08T10:00:00Z",
    isPublished: true,
    isHot: true,
    authorHandle: "arjun",
    authorName: "Arjun Menon",
    authorAvatarUrl: null,
    heroPhotoRef: IMG.bar1,
  },
  {
    id: "dev-3",
    title: "Street Food Trail",
    description: "The real Bangalore food tour — VV Puram to Jayanagar and beyond",
    slug: "street-food-trail",
    emoji: "🌮",
    coverStyle: 2,
    placeCount: 15,
    saveCount: 203,
    createdAt: "2026-05-06T10:00:00Z",
    isPublished: true,
    isHot: true,
    authorHandle: "meera",
    authorName: "Meera Iyer",
    authorAvatarUrl: null,
    heroPhotoRef: IMG.food1,
  },
  {
    id: "dev-4",
    title: "Hidden Gems in Indiranagar",
    description: "Beyond the 12th Main hype — the places only locals know about",
    slug: "hidden-gems-indiranagar",
    emoji: "🍕",
    coverStyle: 3,
    placeCount: 9,
    saveCount: 67,
    createdAt: "2026-05-04T10:00:00Z",
    isPublished: true,
    isHot: false,
    authorHandle: "karthik",
    authorName: "Karthik Rao",
    authorAvatarUrl: null,
    heroPhotoRef: IMG.pizza1,
  },
  {
    id: "dev-5",
    title: "Weekend Breakfast",
    description: "Where I go when sleeping in means brunch by 11",
    slug: "weekend-breakfast",
    emoji: "🥐",
    coverStyle: 4,
    placeCount: 7,
    saveCount: 54,
    createdAt: "2026-05-02T10:00:00Z",
    isPublished: true,
    isHot: false,
    authorHandle: "nisha",
    authorName: "Nisha Patel",
    authorAvatarUrl: null,
    heroPhotoRef: IMG.brunch1,
  },
  {
    id: "dev-6",
    title: "Craft Beer Crawl",
    description: "Koramangala to Whitefield — every taproom worth visiting",
    slug: "craft-beer-crawl",
    emoji: "🍻",
    coverStyle: 0,
    placeCount: 11,
    saveCount: 118,
    createdAt: "2026-04-28T10:00:00Z",
    isPublished: true,
    isHot: true,
    authorHandle: "rahul",
    authorName: "Rahul Dev",
    authorAvatarUrl: null,
    heroPhotoRef: IMG.beer1,
  },
  {
    id: "dev-7",
    title: "Italian Done Right",
    description: "Proper pasta, real wood-fired ovens, and zero fusion confusion",
    slug: "italian-done-right",
    emoji: "🍝",
    coverStyle: 1,
    placeCount: 6,
    saveCount: 45,
    createdAt: "2026-04-25T10:00:00Z",
    isPublished: true,
    isHot: false,
    authorHandle: "priya",
    authorName: "Priya Sharma",
    authorAvatarUrl: null,
    heroPhotoRef: IMG.italian1,
  },
  {
    id: "dev-8",
    title: "Late Night Eats",
    description: "The city after midnight — where to go when hunger strikes at 1 AM",
    slug: "late-night-eats",
    emoji: "🌙",
    coverStyle: 2,
    placeCount: 10,
    saveCount: 76,
    createdAt: "2026-04-20T10:00:00Z",
    isPublished: true,
    isHot: false,
    authorHandle: "arjun",
    authorName: "Arjun Menon",
    authorAvatarUrl: null,
    heroPhotoRef: IMG.late1,
  },
  {
    id: "dev-9",
    title: "Sweet Tooth Tour",
    description: "Bakeries, dessert bars, and ice cream worth the calories",
    slug: "sweet-tooth-tour",
    emoji: "🍰",
    coverStyle: 3,
    placeCount: 8,
    saveCount: 93,
    createdAt: "2026-04-18T10:00:00Z",
    isPublished: true,
    isHot: false,
    authorHandle: "nisha",
    authorName: "Nisha Patel",
    authorAvatarUrl: null,
    heroPhotoRef: IMG.dessert1,
  },
];

export const DEV_HOME_LISTS = [
  {
    id: "dev-1",
    title: "Best Coffee in Bangalore",
    slug: "best-coffee-bangalore",
    emoji: "☕",
    description: "From pour-overs to filter kaapi",
    placeCount: 8,
    isPublished: true,
    updatedAt: "2026-05-22T14:30:00Z",
    heroPhotoRef: IMG.coffee1,
    coverStyle: 0,
  },
  {
    id: "dev-2",
    title: "Date Night Spots",
    slug: "date-night-spots",
    emoji: "🍸",
    description: "Candlelit corners and rooftop cocktails",
    placeCount: 8,
    isPublished: true,
    updatedAt: "2026-05-20T18:00:00Z",
    heroPhotoRef: IMG.bar1,
    coverStyle: 1,
  },
  {
    id: "dev-7",
    title: "Italian Done Right",
    slug: "italian-done-right",
    emoji: "🍝",
    description: "Proper pasta, real wood-fired ovens",
    placeCount: 6,
    isPublished: true,
    updatedAt: "2026-05-18T09:00:00Z",
    heroPhotoRef: IMG.italian1,
    coverStyle: 1,
  },
  {
    id: "dev-draft-1",
    title: "Rooftop Bars",
    slug: null,
    emoji: "🏙️",
    description: "Still scouting the best ones",
    placeCount: 3,
    isPublished: false,
    updatedAt: "2026-05-21T20:00:00Z",
    heroPhotoRef: IMG.bar2,
    coverStyle: 2,
  },
  {
    id: "dev-draft-2",
    title: "Koramangala Lunch Spots",
    slug: null,
    emoji: "🍱",
    description: null,
    placeCount: 2,
    isPublished: false,
    updatedAt: "2026-05-19T12:00:00Z",
    heroPhotoRef: IMG.food3,
    coverStyle: 3,
  },
];

export const DEV_PROFILE = {
  id: "dev-user-id",
  handle: "priya",
  displayName: "Priya Sharma",
  bio: "Food explorer, coffee snob, and weekend brunch enthusiast. I eat so you don't have to waste a meal.",
  avatarUrl: null,
  avatarTint: 0,
  listCount: 5,
  city: "Bangalore",
};

export const DEV_PROFILE_LISTS = [
  {
    id: "dev-1",
    title: "Best Coffee in Bangalore",
    slug: "best-coffee-bangalore",
    emoji: "☕",
    description: "From pour-overs to filter kaapi",
    placeCount: 8,
    coverStyle: 0,
    isPublished: true,
    heroPhotoRef: IMG.coffee1,
  },
  {
    id: "dev-7",
    title: "Italian Done Right",
    slug: "italian-done-right",
    emoji: "🍝",
    description: "Proper pasta, real wood-fired ovens",
    placeCount: 6,
    coverStyle: 1,
    isPublished: true,
    heroPhotoRef: IMG.italian1,
  },
  {
    id: "dev-5",
    title: "Weekend Breakfast",
    slug: "weekend-breakfast",
    emoji: "🥐",
    description: "Where I go when sleeping in means brunch by 11",
    placeCount: 7,
    coverStyle: 4,
    isPublished: true,
    heroPhotoRef: IMG.brunch1,
  },
];

export const DEV_TASTE_SIGNALS = {
  topNeighborhoods: ["Koramangala", "Indiranagar", "Jayanagar"],
  topCuisines: ["cafe", "Italian", "bakery"],
  totalPlaceCount: 21,
  mosaicPhotos: [
    IMG.coffee1,
    IMG.italian1,
    IMG.brunch1,
    IMG.coffee2,
    IMG.food2,
    IMG.dessert1,
  ],
};

export const DEV_LIST_DETAIL = {
  list: {
    title: "Best Coffee in Bangalore",
    description: "From pour-overs to filter kaapi — the spots that keep me caffeinated. Every single one tested on multiple visits, across seasons, with different people. This isn't a Google Maps list — it's a love letter to Bangalore's coffee scene.",
    emoji: "☕",
    coverStyle: 0,
    placeCount: 8,
    createdAt: "2026-05-10T10:00:00Z",
  },
  places: [
    {
      id: "place-1",
      name: "Third Wave Coffee",
      area: "Koramangala, 4th Block",
      cuisines: ["cafe", "coffee"],
      photoRef: IMG.coffee1,
      note: "The cold brew here changed my life. Get the one with oat milk — trust me. The outdoor seating at 7 AM is pure magic.",
      position: 0,
    },
    {
      id: "place-2",
      name: "Blue Tokai",
      area: "Indiranagar, 12th Main",
      cuisines: ["cafe", "coffee", "bakery"],
      photoRef: IMG.coffee2,
      note: "Their single-origin pour-over is the best in the city. The baristas actually know what they're doing. Ask for the seasonal blend.",
      position: 1,
    },
    {
      id: "place-3",
      name: "Subko Coffee",
      area: "Church Street",
      cuisines: ["cafe", "coffee"],
      photoRef: IMG.coffee3,
      note: "Bombay transplant that brought the specialty coffee game to Bangalore. The espresso tonic on a hot day is *chef's kiss*.",
      position: 2,
    },
    {
      id: "place-4",
      name: "Dyu Art Cafe",
      area: "Koramangala, 5th Block",
      cuisines: ["cafe", "continental"],
      photoRef: IMG.coffee4,
      note: "Not just coffee — it's an experience. Art on the walls, a courtyard with fairy lights, and a cappuccino that tastes like someone cared.",
      position: 3,
    },
    {
      id: "place-5",
      name: "Hatti Kaapi",
      area: "Basavanagudi, Gandhi Bazaar",
      cuisines: ["south_indian", "coffee"],
      photoRef: IMG.coffee5,
      note: "Forget fancy pour-overs — this is filter kaapi the way your grandmother made it. Strong, sweet, served in a steel tumbler. ₹15 and life makes sense again.",
      position: 4,
    },
    {
      id: "place-6",
      name: "Café Pascucci",
      area: "Indiranagar, CMH Road",
      cuisines: ["cafe", "italian"],
      photoRef: IMG.coffee6,
      note: "Italian-style espresso bar. The macchiato is perfect — not the Starbucks kind, the real 2-sip Italian kind.",
      position: 5,
    },
    {
      id: "place-7",
      name: "Matteo Coffea",
      area: "Church Street",
      cuisines: ["cafe", "coffee", "bakery"],
      photoRef: IMG.food6,
      note: "Go for the flat white, stay for the banana bread. Window seat on a rainy day is the best therapy this city offers.",
      position: 6,
    },
    {
      id: "place-8",
      name: "Brahmin's Coffee Bar",
      area: "Basavanagudi, Shankarapuram",
      cuisines: ["south_indian", "coffee"],
      photoRef: IMG.street1,
      note: "The idli-vada-coffee combo at 7:30 AM. Standing room only. No menu, no choices, no Wi-Fi. Just perfection since 1960.",
      position: 7,
    },
  ],
  author: {
    handle: "priya",
    displayName: "Priya Sharma",
    avatarUrl: null,
    city: "bangalore",
  },
  slug: "best-coffee-bangalore",
};
